"""initial schema

Revision ID: e8b82700ce79
Revises: 
Create Date: 2026-06-15 16:38:02.816381
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = 'e8b82700ce79'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('email', name=op.f('uq_app_user_email'))
    )
    op.create_table('category',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('domain_applicability', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('scope', sa.Integer(), nullable=True),
    sa.Column('default_unit', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('scope is null or scope in (1,2,3)', name=op.f('ck_category_scope_valid')),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], name=op.f('fk_category_parent_id_category'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category')),
    sa.UniqueConstraint('code', name=op.f('uq_category_code'))
    )
    op.create_table('factor_source',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('credibility_tier', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('credibility_tier in (1, 2)', name=op.f('ck_factor_source_credibility_tier_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_factor_source'))
    )
    op.create_table('gas',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gas')),
    sa.UniqueConstraint('symbol', name=op.f('uq_gas_symbol'))
    )
    op.create_table('gwp_set',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('horizon_years', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gwp_set')),
    sa.UniqueConstraint('name', name=op.f('uq_gwp_set_name'))
    )
    op.create_table('emission_factor',
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('gas_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=60), nullable=False),
    sa.Column('region', sa.String(length=40), nullable=False),
    sa.Column('gwp_basis', sa.String(length=20), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('dist_type', sa.String(length=20), nullable=True),
    sa.Column('dist_params', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('uncertainty_pct', sa.Float(), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('tier is null or tier in (1,2,3)', name=op.f('ck_emission_factor_tier_valid')),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_emission_factor_category_id_category'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gas_id'], ['gas.id'], name=op.f('fk_emission_factor_gas_id_gas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['factor_source.id'], name=op.f('fk_emission_factor_source_id_factor_source'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emission_factor')),
    sa.UniqueConstraint('category_id', 'gas_id', 'region', 'version', name='factor_version')
    )
    with op.batch_alter_table('emission_factor', schema=None) as batch_op:
        batch_op.create_index('ix_factor_active_lookup', ['category_id', 'region', 'is_active'], unique=False)

    op.create_table('gwp_value',
    sa.Column('gwp_set_id', sa.Uuid(), nullable=False),
    sa.Column('gas_id', sa.Uuid(), nullable=False),
    sa.Column('gwp', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['gas_id'], ['gas.id'], name=op.f('fk_gwp_value_gas_id_gas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gwp_set_id'], ['gwp_set.id'], name=op.f('fk_gwp_value_gwp_set_id_gwp_set'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gwp_value')),
    sa.UniqueConstraint('gwp_set_id', 'gas_id', name='gwp_set_gas')
    )
    op.create_table('project',
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=20), nullable=False),
    sa.Column('region', sa.String(length=40), nullable=False),
    sa.Column('reporting_period_start', sa.Date(), nullable=True),
    sa.Column('reporting_period_end', sa.Date(), nullable=True),
    sa.Column('base_year', sa.Integer(), nullable=True),
    sa.Column('gwp_set_id', sa.Uuid(), nullable=False),
    sa.Column('functional_unit', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gwp_set_id'], ['gwp_set.id'], name=op.f('fk_project_gwp_set_id_gwp_set'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['app_user.id'], name=op.f('fk_project_owner_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project'))
    )
    op.create_table('activity_record',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=60), nullable=False),
    sa.Column('period', sa.String(length=40), nullable=True),
    sa.Column('domain_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('data_origin', sa.String(length=20), nullable=False),
    sa.Column('activity_uncertainty', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_activity_record_category_id_category'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_activity_record_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_record'))
    )
    op.create_table('calculation_run',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gwp_set_id', sa.Uuid(), nullable=False),
    sa.Column('methodology_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('uncertainty_method', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['gwp_set_id'], ['gwp_set.id'], name=op.f('fk_calculation_run_gwp_set_id_gwp_set'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_calculation_run_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calculation_run'))
    )
    op.create_table('scenario',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('overrides', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_scenario_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario'))
    )
    op.create_table('calculation_result',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('activity_record_id', sa.Uuid(), nullable=False),
    sa.Column('strategy_used', sa.String(length=80), nullable=False),
    sa.Column('factor_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('co2e_kg', sa.Float(), nullable=False),
    sa.Column('co2e_uncertainty', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('assumptions', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['activity_record_id'], ['activity_record.id'], name=op.f('fk_calculation_result_activity_record_id_activity_record'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['calculation_run.id'], name=op.f('fk_calculation_result_run_id_calculation_run'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calculation_result'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calculation_result')
    op.drop_table('scenario')
    op.drop_table('calculation_run')
    op.drop_table('activity_record')
    op.drop_table('project')
    op.drop_table('gwp_value')
    with op.batch_alter_table('emission_factor', schema=None) as batch_op:
        batch_op.drop_index('ix_factor_active_lookup')

    op.drop_table('emission_factor')
    op.drop_table('gwp_set')
    op.drop_table('gas')
    op.drop_table('factor_source')
    op.drop_table('category')
    op.drop_table('app_user')
    # ### end Alembic commands ###
